### PR TITLE
Array.iterate_with_xml applies attributes even when `unwrap: true`

### PR DESCRIPTION
**Pull request by jpmoral**
This is an attempt to address #56.

@drakmail, @tjarratt please see if this is any good and doesn't break anything.

### CODE REVIEW

**Comment by drakmail** [comment]
@jpmoral thank you! I'll check it at this week.

**Comment by bergholdt** [comment]
Any reason this fix has not been accepted?

Would be nice to have this in savon2 as well.

**Comment by netmask** [comment]
any time frame to get this merged ?

**Comment by tjarratt** [comment]
The easy answer is that I really haven't had time to maintain and provide much care and feeding to Gyoku and the other Savon projects ever since my son was born.

Merging this seems like a fairly easy activity, so I'm happy to do this today, because it will take my mind off some things.

In the long term, I really need to find someone (or several people) that are interested in maintaining Savon and its related projects.

**Comment by tjarratt** [comment]
Merged this from the command line, because of merge conflicts.

Sorry for the delay in getting this merged, and thank you for contributing this fix @jpmoral!

**Comment by jpmoral** [comment]
@tjarratt that's cool, thanks for merging!

**Pull request closed without merging**
